// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzZXiXunAE3_znMVH7o_lj4hH1Ob2KEWk',
    appId: '1:815352042500:web:395555ef16b23003a45151',
    messagingSenderId: '815352042500',
    projectId: 'lawyer-hiring-app-b3415',
    authDomain: 'lawyer-hiring-app-b3415.firebaseapp.com',
    storageBucket: 'lawyer-hiring-app-b3415.firebasestorage.app',
    measurementId: 'G-HJMPN4LZGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI0xmXTr3LmaYndAr-haDINqx9fqN_bHo',
    appId: '1:815352042500:android:ec56111f89026459a45151',
    messagingSenderId: '815352042500',
    projectId: 'lawyer-hiring-app-b3415',
    storageBucket: 'lawyer-hiring-app-b3415.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI0xmXTr3LmaYndAr-haDINqx9fqN_bHo',
    appId: '1:815352042500:ios:ec56111f89026459a45151',
    messagingSenderId: '815352042500',
    projectId: 'lawyer-hiring-app-b3415',
    storageBucket: 'lawyer-hiring-app-b3415.firebasestorage.app',
    iosBundleId: 'com.example.lawhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI0xmXTr3LmaYndAr-haDINqx9fqN_bHo',
    appId: '1:815352042500:ios:ec56111f89026459a45151',
    messagingSenderId: '815352042500',
    projectId: 'lawyer-hiring-app-b3415',
    storageBucket: 'lawyer-hiring-app-b3415.firebasestorage.app',
    iosBundleId: 'com.example.lawhub.RunnerTests',
  );
}
