// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRLhOYqDi9di_IvZydoEW4WjTMQIbt78k',
    appId: '1:1008692904258:web:2befbac0f059e4cb8c48db',
    messagingSenderId: '1008692904258',
    projectId: 'lawhub-85521',
    authDomain: 'lawhub-85521.firebaseapp.com',
    storageBucket: 'lawhub-85521.appspot.com',
    measurementId: 'G-HJMPN4LZGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZZsqNWc33EyyAcdsusZjvMAV2B_Q-ASs',
    appId: '1:1008692904258:android:a1fcd214d7f729ba8c48db',
    messagingSenderId: '1008692904258',
    projectId: 'lawhub-85521',
    storageBucket: 'lawhub-85521.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc17iUOAuBsVV_F6t5MXXfpt2zyuxiCuo',
    appId: '1:1008692904258:ios:b53e905d2719d9478c48db',
    messagingSenderId: '1008692904258',
    projectId: 'lawhub-85521',
    storageBucket: 'lawhub-85521.appspot.com',
    iosBundleId: 'com.example.lawhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc17iUOAuBsVV_F6t5MXXfpt2zyuxiCuo',
    appId: '1:1008692904258:ios:1e14e1282b93a8d68c48db',
    messagingSenderId: '1008692904258',
    projectId: 'lawhub-85521',
    storageBucket: 'lawhub-85521.appspot.com',
    iosBundleId: 'com.example.lawhub.RunnerTests',
  );
}
